# Python CircleCI 2.0 configuration file
#
version: 2
jobs:
  build_and_test:
    machine:
      image: circleci/classic:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build Image for Test
          command: |-
            docker-compose -f tests/docker-compose.yaml build

      - store_artifacts:
          path: test-reports
          destination: test-reports
